0_zlel_V_R_Q.cir tiene transistor 
0_zlel_OPAMP.cir tiene opamp


In [1]:
import numpy as np

In [18]:
dokumento="0_zlel_V_R_Q.cir"
with open(dokumento, 'r', encoding='utf-8') as file:
    contenido = file.read()
print(contenido)

V_1 1 0 0 0 10 0 0 0 
R_1 1 2 0 0 1e3 0 0 0 
R_2 2 20 0 0 2e3 0 0 0 
R_4 0 20 0 0 4e3 0 0 0 
Q_1 2 20 0 0 7e-14 1e-13 100 0
R_3 2 7 0 0 1E3 0 0 0 
r_ab 7 0 0 0 200 0 0 0 
g_m 0 7 0 0 4 0 0 R_3
.pr 0 0 0 0 0 0 0 0



In [19]:
#hau ez erabili, zuzenenan bestean
def dokumentutik_matrizea_atera(dokumentua):
    componentes = []
    with open(dokumentua, "r") as f:
        for linea in f:
            linea = linea.strip()
            if not linea:
                continue
            if linea.startswith("."):
                continue

            partes = linea.split()
            print(partes)

            #ignorar títulos (una sola palabra)
            if len(partes) < 4:
                continue

            nombre = partes[0]
            nodo1 = int(partes[1])
            nodo2 = int(partes[2])
            nodo3 = int(partes[3]) 
            nodo4 = int(partes[4])
            valor1 = float(partes[5])
            valor2 = float(partes[6])
            valor3 = float(partes[7])
            kontrol = partes[8]

            componentes.append((nombre, nodo1, nodo2, nodo3, nodo4, valor1, valor2, valor3, kontrol))
    return componentes

In [4]:
info_matrizea=dokumentutik_matrizea_atera("0_zlel_OPAMP.cir")

['A_10', '1', '2', '3', '0', '0', '0', '0', '0']
['V_10', '1', '0', '0', '0', '10', '0', '0', '0']
['R_40', '2', '0', '0', '0', '4E3', '0', '0', '0']
['r_10', '3', '5', '0', '0', '1e3', '0', '0', '0']
['r_20', '5', '4', '0', '0', '2e30', '0', '0', '0']
['r_30', '4', '2', '0', '0', '3e30', '0', '0', '0']
['A_20', '0', '5', '4', '0', '0', '0', '0', '0']


In [4]:
def dokumentutik_matrizeak_atera(dokumentua):
    componentes = []
    with open(dokumentua, "r") as f:
        for linea in f:
            linea = linea.strip()
            if not linea:
                continue
            if linea.startswith("."):
                continue

            partes = linea.split()
            print(partes)

            #ignorar títulos (una sola palabra)
            if len(partes) < 4:
                continue

            nombre = partes[0]
            nodo1 = int(partes[1])
            nodo2 = int(partes[2])
            nodo3 = int(partes[3]) 
            nodo4 = int(partes[4])
            valor1 = float(partes[5])
            valor2 = float(partes[6])
            valor3 = float(partes[7])
            kontrol = partes[8]

            componentes.append((nombre, nodo1, nodo2, nodo3, nodo4, valor1, valor2, valor3, kontrol))
            #2garren zatia
            cir_el_lista=[]
            cir_nd_lista=[]
            cir_val_lista=[]
            cir_ctrl_lista=[]
            for lista in componentes:
                cir_el_lista.append(lista[0])
                cir_el=np.array(cir_el_lista) #para pasar la lista a array
                cir_el=cir_el.reshape(-1,1) #para poner la matriz en columna

                #PARA HACER NODOAK TIENE QUE TENER 4 COLUMAS, SI NO TIENE 4 COLUMAS, HAY QUE RELLENAR CON CEROS
                cir_nd_lista.append(lista[1:5]) 
                cir_nd=np.array(cir_nd_lista) 

                #balioak lo mismo
                cir_val_lista.append(lista[5:8])
                cir_val=np.array(cir_val_lista)

                cir_ctrl_lista.append(lista[8])
                cir_ctrl=np.array(cir_ctrl_lista)
                cir_ctrl=cir_ctrl.reshape(-1,1)

        return cir_el, cir_nd, cir_val, cir_ctrl


In [42]:
#aldagaiak definitu
cir_el, cir_nd, cir_val, cir_ctrl = dokumentutik_matrizeak_atera("0_zlel_V_R_Q.cir")
print(cir_el)

['V_1', '1', '0', '0', '0', '10', '0', '0', '0']
['R_1', '1', '2', '0', '0', '1e3', '0', '0', '0']
['R_2', '2', '20', '0', '0', '2e3', '0', '0', '0']
['R_4', '0', '20', '0', '0', '4e3', '0', '0', '0']
['Q_1', '2', '20', '0', '0', '7e-14', '1e-13', '100', '0']
['R_3', '2', '7', '0', '0', '1E3', '0', '0', '0']
['r_ab', '7', '0', '0', '0', '200', '0', '0', '0']
['g_m', '0', '7', '0', '0', '4', '0', '0', 'R_3']
[['V_1']
 ['R_1']
 ['R_2']
 ['R_4']
 ['Q_1']
 ['R_3']
 ['r_ab']
 ['g_m']]


In [35]:
a= dokumentutik_matrizeak_atera("0_zlel_OPAMP.cir")
print(a) #LA FORMA QUE DEVUELVE SE PUEDE MEJORAR SEGURO
#b=print(cir_el)

['A_10', '1', '2', '3', '0', '0', '0', '0', '0']
['V_10', '1', '0', '0', '0', '10', '0', '0', '0']
['R_40', '2', '0', '0', '0', '4E3', '0', '0', '0']
['r_10', '3', '5', '0', '0', '1e3', '0', '0', '0']
['r_20', '5', '4', '0', '0', '2e30', '0', '0', '0']
['r_30', '4', '2', '0', '0', '3e30', '0', '0', '0']
['A_20', '0', '5', '4', '0', '0', '0', '0', '0']
(array([['A_10'],
       ['V_10'],
       ['R_40'],
       ['r_10'],
       ['r_20'],
       ['r_30'],
       ['A_20']], dtype='<U4'), array([[1, 2, 3, 0],
       [1, 0, 0, 0],
       [2, 0, 0, 0],
       [3, 5, 0, 0],
       [5, 4, 0, 0],
       [4, 2, 0, 0],
       [0, 5, 4, 0]]), array([[0.e+00, 0.e+00, 0.e+00],
       [1.e+01, 0.e+00, 0.e+00],
       [4.e+03, 0.e+00, 0.e+00],
       [1.e+03, 0.e+00, 0.e+00],
       [2.e+30, 0.e+00, 0.e+00],
       [3.e+30, 0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00]]), array([['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0']], dtype='<U1'))


In [46]:
def elementu_bereziak(cir_el, cir_nd):  #cuando hay 2 elementos solo identifica 1
    elementu_berezien_zerrenda=[]
    hiztegi_transistor={}
    hiztegi_diodo={}
    hiztegi_opamp={}
    nodos_transistor=[]
    nodos_diodo=[]
    nodos_opamp=[]
    for elem, lista in zip(cir_el, cir_nd):
        for letra in elem:
            if letra.startswith("Q"):
                nodos_transistor=lista
                hiztegi_transistor["N_kolektor"]=nodos_transistor[0]
                hiztegi_transistor["N_oinarri"]=nodos_transistor[1]
                hiztegi_transistor["N_igorle"]=nodos_transistor[2]
                #return(elem, hiztegi_transistor)
                elementu_berezien_zerrenda.append(hiztegi_transistor)

            elif letra.startswith("D"):
                nodos_diodo=lista
                hiztegi_diodo["N_terminal+"]=nodos_diodo[0]
                hiztegi_diodo["N_terminal-"]=nodos_diodo[1]
                #return(elem, hiztegi_diodo)
                elementu_berezien_zerrenda.append(hiztegi_diodo)
            elif letra.startswith("A"):
                hiztegi_opamp={}
                nodos_opamp=lista
                hiztegi_opamp["N+"]=nodos_opamp[0]
                hiztegi_opamp["N-"]=nodos_opamp[1]
                hiztegi_opamp["N_out"]=nodos_opamp[2]
                hiztegi_opamp["N_ref(0)"]=nodos_opamp[3]
                #return(elem, hiztegi_opamp)
                elementu_berezien_zerrenda.append(hiztegi_opamp)
    return elementu_berezien_zerrenda
        

In [47]:
berezi_elem_nodo = elementu_bereziak(cir_el, cir_nd)
#print(len(berezi_elem_nodo))
print(berezi_elem_nodo)
#print(berezi_elem_nodo[1].values())


[{'N_kolektor': 2, 'N_oinarri': 20, 'N_igorle': 0}]


1. branch : A_10_in i1 v1 = e1 - e2
2. branch : A_10_ou i2 v2 = e3 - e0
8. branch : A_20_in i8 v8 = e0 - e5
9. branch : A_20_ou i9 v9 = e4 - e0

In [32]:
berezi_elem_nodo = elementu_bereziak(cir_el, cir_nd)
print(berezi_elem_nodo[1])

{'N_kolektor': 2, 'N_oinarri': 20, 'N_igorle': 0}


In [ ]:
#ESTE CASO ES EL QUE FUNCIONA
berezi_elem_nodo = elementu_bereziak(cir_el, cir_nd)
#elementu_berezien_nodoa_lista=elementu_bereziak(cir_el, cir_nd)
elementu_berezi_kop=len(berezi_elem_nodo)
elem_kont=0
circ_nd_bereziekin=[]
adar_kont=0
circ_nd_bereziekin=[]
elem_berezien_kont=0 #elementu bereziaren zenbakia
#elementu_berezien_nodoak=elementu_bereziak(cir_el, cir_nd)[1].values() #saca el hiztegi de los nodos del elemento berezi y luego sus valores
#print("Branches:",elem_zenb+1) esto tienes que contarlo mas tarde
for branch, lista in zip(cir_el, cir_nd):
    #for i in range(elementu_berezi_kop): 
        if branch[0].startswith("A"):
            adar_kont+=1
            nplus=berezi_elem_nodo[elem_berezien_kont]["N+"]
            nminus=berezi_elem_nodo[elem_berezien_kont]["N-"]
            n_out=berezi_elem_nodo[elem_berezien_kont]["N_out"]
            n_ref=berezi_elem_nodo[elem_berezien_kont]["N_ref(0)"]
            circ_nd_bereziekin.append((int(nminus),int(n_out)))
            print(f" {adar_kont} branch:  {branch[0]}_in    i{adar_kont}     v{adar_kont} = e{nplus} - e{nminus}")
            adar_kont+=1
            circ_nd_bereziekin.append((int(nminus),int(n_out)))
            print(f" {adar_kont} branch:  {branch[0]}_out  i{adar_kont}     v{adar_kont} = e{n_out} - e{n_ref}")
            elem_berezien_kont+=1
        elif branch[0].startswith("Q"):
            adar_kont+=1
            #oinarri=elementu_berezien_nodoak[elem_berezien_kont]["N_oinarri"] # elementu_berezien_nodoak da error, tienes qie poner berezi_elem_nodo
            oinarri=berezi_elem_nodo[elem_berezien_kont]["N_oinarri"]
            igorle=berezi_elem_nodo[elem_berezien_kont]["N_igorle"]
            kolektor=berezi_elem_nodo[elem_berezien_kont]["N_kolektor"]
            circ_nd_bereziekin.append((int(oinarri),int(igorle))) #en vez de cojer con nombres haz con numeros y fuera
            print(f" {adar_kont} branch:  {branch[0]}_be    i{adar_kont}     v{adar_kont} = e{oinarri} - e{igorle}") #base-igorle
            adar_kont+=1
            circ_nd_bereziekin.append((int(oinarri),int(kolektor)))
            print(f" {adar_kont} branch:  {branch[0]}_bc    i{adar_kont}     v{adar_kont} = e{oinarri} - e{kolektor}")#base-kolektorea 
            elem_berezien_kont+=1 
        elif branch[0].startswith("D"): #N+ N- N_out N_ref(0)
                #EL CASO DE DIODO NO ESTA COMPROBADO, SEGURAMENTE HAYA ALGO MAL
                print("elemento especial diodo:", branch)
                adar_kont+=1
                nplus=berezi_elem_nodo[elem_berezien_kont]["N_terminal+"]
                nminus=berezi_elem_nodo[elem_berezien_kont]["N_terminal-"]
                circ_nd_bereziekin.append((int(oinarri),int(igorle)))
                print(f" {adar_kont} branch:  {branch[0]}_be    i{adar_kont}     v{adar_kont} = e{oinarri} - e{igorle}") #base-igorle
                adar_kont+=1
                circ_nd_bereziekin.append((int(oinarri),int(kolektor)))
                print(f" {adar_kont} branch:  {branch[0]}_bc    i{adar_kont}"                                           )  #SIN ACABAR
                elem_berezien_kont+=1      
        else:
            adar_kont+=1
            circ_nd_bereziekin.append((int(lista[0]),int(lista[1]))) #meter una tupla con los 2 nodos de cada branch normal
            columna1= lista[0]
            columna2=lista[1]
            columna1=columna1.astype(str) #pasalo a str para poderlo concadenar y que quede junto
            columna2=columna2.astype(str)
            print(f" {adar_kont} branch:  {branch[0]}      i{adar_kont}     v{adar_kont} = e{columna1} - e{columna2}")
#print(circ_nd_bereziekin)
#aldagaiak zenbakitu
elem_zenb= cir_el.size
print("      ")
print(elem_zenb," Elements")
nodo_zerrenda=[0] #ponemos del tiron el errefrentzia nodoa xq todos lo tienen no?
for lista in cir_nd:
    for elem in lista:
        if elem != 0 and elem not in nodo_zerrenda:
            nodo_zerrenda.append(elem)
nodo_zerrenda_ordenatua=sorted(nodo_zerrenda)
nodo_zenb= len(nodo_zerrenda)
print(nodo_zenb," Differnt nodes:", np.array(nodo_zerrenda_ordenatua))
aldagaien_zerrenda=[]
for i in range(1, nodo_zenb):
    aldagaien_zerrenda.append(f"e{nodo_zerrenda[i]}")  #igual ordenarlo de pequeño a grande
for i in range(1, adar_kont+1):
    aldagaien_zerrenda.append(f"i{i}")
for i in range(1, adar_kont+1):
    aldagaien_zerrenda.append(f"v{i}")
aldagai_kop=len(aldagaien_zerrenda)
print(aldagai_kop,"Variables:", aldagaien_zerrenda)



 1 branch:  V_1      i1     v1 = e1 - e0
 2 branch:  R_1      i2     v2 = e1 - e2
 3 branch:  R_2      i3     v3 = e2 - e20
 4 branch:  R_4      i4     v4 = e0 - e20
 5 branch:  Q_1_be    i5     v5 = e20 - e0
 6 branch:  Q_1_bc    i6     v6 = e20 - e2
 7 branch:  R_3      i7     v7 = e2 - e7
 8 branch:  r_ab      i8     v8 = e7 - e0
 9 branch:  g_m      i9     v9 = e0 - e7
      
8  Elements
5  Differnt nodes: [ 0  1  2  7 20]
22 Variables: ['e1', 'e2', 'e20', 'e7', 'i1', 'i2', 'i3', 'i4', 'i5', 'i6', 'i7', 'i8', 'i9', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9']


In [ ]:
#ESCRIBIUENDO LA FUNCION
def print_cir_info(cir_el, cir_nd, b, n, nodes, el_num):
    

In [81]:
branch0="A_10"
if branch0.startswith("A"):
    print("empieza x a")


empieza x a


In [53]:
def incidence_matrix(cir_nd, nodo_zerrenda_ordenatua):
    Aa_matriz= []
    #nodo_zerrenda_ordenatua= sorted(nodo_zerrenda). ya la hemos ordenador en la anterior funcion
    for elem in cir_nd:
        lista_A=[]
        for nodo in nodo_zerrenda_ordenatua:
            if elem[0]==nodo:
                lista_A.append(1)
            elif elem[1]==nodo:
                lista_A.append(-1)
            else:
                lista_A.append(0)
        Aa_matriz.append(lista_A)
    Aa_matriz_array=np.array(Aa_matriz)
    Aa_matriz_array_benetakoa= Aa_matriz_array.T
    return Aa_matriz_array_benetakoa

In [54]:
print(incidence_matrix(circ_nd_bereziekin, nodo_zerrenda))

[[-1  0  0  1 -1  0  0 -1  1]
 [ 1  1  0  0  0  0  0  0  0]
 [ 0 -1  1  0  0 -1  1  0  0]
 [ 0  0 -1 -1  1  1  0  0  0]
 [ 0  0  0  0  0  0 -1  1 -1]]


In [55]:
intzidentzia_matrizea= incidence_matrix(circ_nd_bereziekin, nodo_zerrenda)

In [56]:
kont=0
zutabe=[]
for elem in intzidentzia_matrizea:
    zutabe_kop=len(elem)
    if kont<=zutabe_kop:
        zutabe_kop=len(elem)
        #print(elem[kont])
        zutabe.append(elem[kont])
        kont+=1
print(zutabe)

[-1, 1, 1, -1, 0]


In [50]:
zutabe_lista=[]
i=0
for elem in intzidentzia_matrizea:
    print(elem[1])
    zutabe_lista.append(elem[i])
    i=i+1
print(zutabe_lista)

0
1
-1
0
0
[np.int64(-1), np.int64(1), np.int64(1), np.int64(0), np.int64(1)]


In [57]:
intzidentzia_mat_irauli =intzidentzia_matrizea.T
#print(intzidentzia_mat_irauli)
txarto=0
for lista in intzidentzia_mat_irauli:
    #print(lista)
    batuketa=sum(lista)
    #print(batuketa)
    if batuketa!=0:
        print("zerbait txarto dago:(")
        txarto=1
    else:
        continue
if txarto==0:
    print("matrizea ondo")



matrizea ondo


In [58]:
def matrizea_ondo(intzidentzia_matrizea):
    intzidentzia_mat_irauli =intzidentzia_matrizea.T
    txarto=0
    for lista in intzidentzia_mat_irauli:
        batuketa=sum(lista)
        if batuketa!=0:
            print("zerbait txarto dago:(")
            txarto=1
        else:
            continue
    if txarto==0:
        print("matrizea ondo")

    

In [62]:
a=matrizea_ondo(intzidentzia_matrizea)

matrizea ondo
